"use strict";
exports.__esModule = true;
var min_1 = require("./src/min/min");
exports.min = min_1["default"];
var max_1 = require("./src/max/max");
exports.max = max_1["default"];
var plain_matrix_1 = require("./src/plain_matrix/plain_matrix");
exports.plain_matrix = plain_matrix_1["default"];
var sum_1 = require("./src/sum/sum");
exports.sum = sum_1["default"];
var mean_1 = require("./src/mean/mean");
exports.mean = mean_1["default"];
var variance_1 = require("./src/variance/variance");
exports.variance = variance_1["default"];
var standart_deviation_1 = require("./src/standart_deviation/standart_deviation");
exports.standart_deviation = standart_deviation_1["default"];
var z_score_1 = require("./src/z_score/z_score");
exports.z_score = z_score_1["default"];
var median_1 = require("./src/median/median");
console.log(median_1["default"]([1, 2, 3, 4, 5, 6]));
