"use strict";
exports.__esModule = true;
var min_1 = require("./src/min/min");
exports.min = min_1["default"];
var max_1 = require("./src/max/max");
exports.max = max_1["default"];
var plain_matrix_1 = require("./src/plain_matrix/plain_matrix");
exports.plain_matrix = plain_matrix_1["default"];
var sum_1 = require("./src/sum/sum");
console.log(sum_1["default"]([1, 2, 0, 14.543, 12.31321]));
